topic_list = ['Middle Eastern Crisis',
                'Democracy',
                'Crime',
                'Guns',
                'Immigration',
                'Russian-Ukraine War',
                'Environment',
                'Taxes',
                'Education',
                'Trump Legal Troubles',
                '2024 Election',
                'Foreign Policy',
                'Politician',
                'Reproductive Rights',
                'Healthcare',
                'LGBTQ',
                'Transportation',
                'Animals',
                'Arts and Entertainment',
                'Celebrity',
                'Home and Lifestyle',
                'Travel and Tourism',
                'Religion',
                'Holidays',
                'Business - Corporate Strategy',
                'Business - Industry Developments',
                'Health and Wellness',
                'Man-Made Disaster',
                'Weather and Natural Disaster',
                'US Economy',
                'Non-US Economy',
                'Sports - Baseball',
                'Sports - Basketball',
                'Sports - Football',
                'Sports - Other',
                'Science ',
                'Technology']

subtopic_dict = {'Middle Eastern Crisis': ['Israel-Gaza War',
                        'Israel-Lebanon Conflict',
                        'University Campus Activism',
                        'Israel-Iran Conflict'],
                        'Democracy': ['Voting Access/Rights',
                        'Fate of US Democracy',
                        'Election Security'],
                        'Crime': ['Violent Crime',
                        'Financial and Corporate Crime',
                        'Legal Proceedings',
                        'Police Misconduct',
                        'Cybercrime and Security Threats',
                        'Political Corruption',
                        'Terrorism',
                        'Sexual Misconduct',
                        'Drug-Related Crime'],
                        'Guns': ['Gun Legislation and Regulation',
                        'Gun Safety and Violence',
                        'Legal and Societal Implications of Guns',
                        'National Rifle Association (NRA)'],
                        'Immigration': ['Border Security',
                        'Immigration Policy and Reform',
                        'Government Action',
                        'Asylum and Refugees',
                        'Migration Trends'],
                        'Russian-Ukraine War': ['Russian Military Operations',
                        'Ukrainian Military Operations',
                        'Ceasefire Negotiations',
                        'US Foreign Aid'],
                        'Environment': ['Climate Change',
                        'Wildlife Conservation',
                        'Agriculture',
                        'Renewable Energy',
                        'Government Regulation'],
                        'Taxes': ['Tax Policy and Legislation',
                        'IRS and Tax Compliance',
                        'Personal Taxes',
                        'Corporate Taxes'],
                        'Education': ['Diversity and Inclusion',
                        'Student Loans',
                        'Higher Education Policies and Leadership',
                        'Technology and Modern Learning',
                        'Academic Integrity'],
                        'Trump Legal Troubles': ['Jan. 6 Riot',
                        'Supreme Court and Presidential Immunity',
                        'Civil Fraud Trial',
                        'Asset Inflation Case',
                        'Election Subversion Trial',
                        'Classified Material Case',
                        'Hush-Money Scheme',
                        'Real Estate Lawsuits',
                        'Business Tax Disputes'],
                        '2024 Election': ['Presidential Horse Race',
                        'Senate Horse Race',
                        'House Horse Race',
                        'Governor Horse Race',
                        "Biden's Age",
                        'Kamala Harris Campaign',
                        'Voter Concerns'],
                        'Foreign Policy': ['China',
                        'Middle East',
                        'European Union',
                        'Africa',
                        'NATO',
                        'Latin America'],
                        'Politician': ['US House Representative',
                        'US Senator',
                        'State Governor',
                        'US State Official',
                        'Non-US Political Official'],
                        'Reproductive Rights': ['Abortion Regulation',
                        'Abortion and Politics',
                        'Abortion Advocacy and Activism',
                        'Birth Control',
                        'Fertility Treatment'],
                        'Healthcare': ['Health Insurance',
                        'Medical Malpractice',
                        'Government Regulation'],
                        'LGBTQ': ['Transgender Rights', 'Christian Church Divide'],
                        'Transportation': ['Public Transit', 'Transportation Safety'],
                        'Animals': ['Animal Behavior', 'Animal Welfare'],
                        'Arts and Entertainment': ['Art Industry',
                        'Award Show',
                        'TV Industry',
                        'Literature',
                        'Film/Movie Industry',
                        'Fashion Industry',
                        'Music Industry'],
                        'Celebrity': ['Taylor Swift',
                        'Celebrity Relationship',
                        'Celebrity Scandal',
                        'Royal Family'],
                        'Home and Lifestyle': ['Food and Cooking', 'Home Improvement'],
                        'Travel and Tourism': ['Travel Tips'],
                        'Religion': ['Religious Leaders and Influence',
                        'Religion and Social Issues'],
                        'Holidays': ['Gift Ideas', 'Holiday Hours'],
                        'Business - Corporate Strategy': ['Mergers and Acquisitions',
                        'Financial Restructuring',
                        'Company Performance'],
                        'Business - Industry Developments': ['Electric Vehicle Industry',
                        'Retail Industry',
                        'Media Industry',
                        'Tech Industry'],
                        'Health and Wellness': ['COVID-19',
                        'Nutrition and Diet',
                        'Exercise',
                        'Skincare',
                        'Sleep',
                        'Drugs and Alcohol',
                        'Mental Health '],
                        'Man-Made Disaster': ['Airplane Crash', 'Car Accident'],
                        'Weather and Natural Disaster': ['Earthquake',
                        'Heat Wave',
                        'Hurricane',
                        'Wildfire',
                        'Snow Storm',
                        'Flooding'],
                        'US Economy': ['Inflation and Prices',
                        'Monetary Policy',
                        'Stock Market',
                        'Government Spending',
                        'Employment and Wages',
                        'Housing Market',
                        'Consumer Activity',
                        'Trade',
                        'Financial Oversight'],
                        'Non-US Economy': ['China Economy', 'Europe Economy', 'Global Economy'],
                        'Sports - Baseball': ['MLB'],
                        'Sports - Basketball': ['NBA',
                        "Men's College Basketball",
                        "Women's College Basketball",
                        'WNBA'],
                        'Sports - Football': ['NFL', 'College Football'],
                        'Sports - Other': ['NHL',
                        'Soccer',
                        '2024 Olympics',
                        'Golf',
                        'Tennis',
                        'Boxing'],
                        'Science ': ['Astronomy ', 'Paleoanthropology '],
                        'Technology': ['Artificial Intelligence (AI)',
                        'Cybersecurity and Privacy',
                        'Smartphone Technology',
                        'Space and Aerospace Technologies',
                        'Electric Vehicles',
                        'Digital Media and Advertising',
                        'Consumer Technology Trends',
                        'Scientific Exploration and Innovation',
                        'Social Media']}